# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: xenial

addons:
  apt:
    packages:
    - cmake
    - g++

before_install:
  - ./install-treelite.sh
