# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test function
#' 
#' @param path Path to lightGBM model object
#'
#' @return Int
#' @export
#'
#' @examples
#' treelite_test('LightGBM_model.txt')
treelite_test <- function(path) {
    .Call(`_tReelite_treelite_test`, path)
}

